// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypbvkhefhttfjnxkncjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwYnZraGVmaHR0ZmpueGtuY2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTM5MDMsImV4cCI6MjA1ODQ2OTkwM30.XAUrY0js7CjoscXK1yMJ06H7s84GGorTthCZtItO9bE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);